spring.application.name=ImageService_Internship
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5438/Image_DB
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=gallery

spring.liquibase.change-log=classpath:liquibase/changelog-master.xml
spring.liquibase.enabled=true

