spring.application.name=ImageService_Internship
server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

AWS_REGION=${AWS_REGION}
AWS_ENDPOINT=${AWS_ENDPOINT}
AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
AWS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_S3_BUCKET_NAME=${S3_BUCKET}


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=gallery

spring.liquibase.change-log=classpath:liquibase/changelog-master.xml
spring.liquibase.enabled=true

INTERNAL_GATEWAY_KEY=${GATEWAY_KEY}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
likes.kafka.topic=${TOPIC_NAME_COMMENTS}
comments.kafka.topic=${TOPIC_NAME_LIKES}
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=5
